# Generated by Django 5.0.2 on 2024-03-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_profile_image_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.FileField(blank=True, upload_to="profile-images/"),
        ),
    ]
