# Generated by Django 5.0.2 on 2024-03-02 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="link_url",
            field=models.URLField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_platform_url",
                        message="Incorrect URL structure for <django.db.models.fields.CharField>",
                        regex=None,
                    )
                ],
            ),
        ),
    ]
